name: CI

on:
  push:
    branches: moonc-version-dont-delete

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/moonbitlang/moon/actions/workflows/test-on-main.yml/dispatches \
            -d '{"ref":"main"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
